services:
    krista-app:
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - shared
        restart: always
        ports:
            - "1234:1234"

networks:
    shared:
        external: true
        driver: bridge
        name: internal