services:
    krista-app:
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - internal
        restart: always
        ports:
            - "1234:1234"
